### ISSUE TITLE
Add "Delivery to lockers" app to repository

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#10]
We need to add Lightning app "Delivery to lockers" #5 to the repository. Create a pull request.

**Comment by SashaYan10** [comment]
Created a pull request for the Lightning App "Delivery to lockers".

**Comment by msenyk** [comment]
Please look at the comment in pull request

**Comment by SashaYan10** [comment]
Created a pull request for the Lightning App "Delivery to lockers", including the xml file for the app and its custom icon.

**Comment by msenyk** [comment]
Look at the comment in pull request

**Comment by SashaYan10** [comment]
The Custom Tab was added in repository.

**Comment by msenyk** [comment]
@SashaYan10 I still get an error but different one:

    Error Delivery_to_lockers In field: logo - no ContentAsset named IconAppParcelLocker found 

Check the Setup / Asset Files. You should include it in pull request instead of static resource.

**Comment by SashaYan10** [comment]
Added the icon as a Content Asset for the Lightning App.
