### ISSUE TITLE
We need to define manual steps of creating Order

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#15]
We need to describe all steps that CRM user has to do to create Order from scratch. Test it in the org starting from creating a new Opportunity record and adding few Opportunity Products. Write down all steps in the comment to this issue.

**Comment by SashaYan10** [comment]
The steps for manually creating an Order have been defined, starting from creating a new Opportunity, adding Opportunity Products, and proceeding to Order creation and activation.
Here is an extended description of the steps:

1. Creating a New Opportunity. The user fills out the required fields such as Opportunity Name, Close Date, Stage, and any other required information.
For example, created an Opportunity: "sForce Corp - Test Opportunity", Close Date: 12/15/2024, Stage: Prospecting.

2. Adding Products to the Opportunity. On the Opportunity page, in the Related List "Products", the user selects the desired Price Book, chooses products from the catalog they wish to add, then specifies the quantity and price for each product.
For example, added the products "GenWatt Diesel 1000kW", Quantity: 1, "GenWatt Diesel 10kW", Quantity: 1.

3. Creating an Order. Before this, create a Contract for the client (if not yet created), then on the Opportunity page in the Related List "Orders", the user creates a new order, filling in required fields such as Account Name, Order Start Date, Contract Number, Status, and any other required information.
For example, created an order with Account Name: sForce, Order Start Date: 12/09/2024, Contract Number: 00000100, Status: Draft.

4. Adding Products to the Order. In the Related List "Order Products", the user adds products that were specified in the opportunity or adds them from the catalog, specifying the quantity and price.
For example, added the products "GenWatt Diesel 1000kW", Quantity: 1, "GenWatt Diesel 10kW", Quantity: 1.

5. Activating the Order. If the user has verified that all data is correct, they change the order status to "Active".

6. All other actions related to parcel distribution via parcel lockers.

**Comment by msenyk** [comment]
Item 4 is not right. It is standard flow of creating order. But in our example we are using Opportunity Products for Order.

**Comment by Roman45321** [comment]
Steps of creating Order has been edited
