### ISSUE TITLE
I want to know dimention of the order WxHxD (simple version)

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#16]
Majority of the clients order have a single item. We want to know the size of the box (parcel) at Order level.
If Order has more than 1 item - do not calculate the box size automatically. Leave these fields for manual editing.
Do not allow to activate order if the box size is not populated.

**Comment by SashaYan10** [comment]
A Flow has been created to automatically calculate the box dimensions at the time Order creation.

**Comment by msenyk** [comment]
This task is only partially done. We need to add validation to check if Order dimension is populated before activating. And move changes to pull request.

**Comment by SashaYan10** [comment]
Created a pull request for the dimension of the order with all requirements.
