### ISSUE TITLE
Do not place large parcels in small cells

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#17]
The system should validate creation of Cell Order record and compare dimensions of Parcel and Call. The cell must be bigger than parcel. Show the following error message when user tries to put large parcel into small cell:
`This cell is not large enough to store this package.`

Let assume that we can freely rotate the parcel.

**Comment by Roman45321** [comment]
The trigger has been created to validate parcel dimensions and check if the parcel fits into the specified cell.

Trigger classes:
CellOrderTrigger
CellOrderHandler
CellOrderHelper
CellOrderHandlerTest
CellOrderHelperTest

Added changes to https://github.com/msenyk/sf-practicum-2024/pull/31 pull request.

**Comment by Roman45321** [comment]
Necessary changes have been made to the CellOrderTriggerHelper class.

**Comment by Roman45321** [comment]
Moved trigger logic to `after` phase, combined both objects in a single query, added comparing ID with null

**Comment by Roman45321** [comment]
Removed unnecessary check for null, fixed issues in unit-tests
