### ISSUE TITLE
Modify Cell Order object to allow delivery to Parcel Locker even if all cells are closed

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#18]
At the time of creating Order we do not know if there is a free place in Parcel Locker. The delivery service can only check cells when the van has stopped near the locker.
Improve data integrity by:

1. For statuses "Pending delivery" and "Delivering" don't allow to populate Cell field, only Parcel Locker
2. Do not allow to save record with "Delivered" status if Cell field is empty
3. Cell field should match the Parcel Locker
4. After saved record with "Delivered" status - make all field read only. It is possible to change only Status to "Completed"

**Comment by Roman45321** [comment]
Added validation rules:
- "Disallow_populating_Cell_field" - prohibits selecting a cell when the order status is "Pending delivery" or "Delivering", only Parcel Locker.
- "Require_Cell_for_delivered_status" - prohibits the absence of a value in the Cell field when the order status is "Delivered" or "Completed".
- "Ensure_Cell_matches_parcel_locker" - checks if the cell matches the selected Parcel Locker.
- "Lock_fields_after_delivery_completed" - prohibits editing fields other than status, when the order status is "Delivered" or "Completed".

Added changes to https://github.com/msenyk/sf-practicum-2024/pull/34 pull request.

**Comment by msenyk** [comment]
@Roman45321 Please, resolve conflicts in https://github.com/msenyk/sf-practicum-2024/pull/34 pull request

**Comment by Roman45321** [comment]
Resolved conflicts with main branch in Order__c.field-meta.xml
