### ISSUE TITLE
Check sizes and quantity of cells of real parcel locker

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#2]
We need to know how many small, medium and big cells there are.
Which is the size of each cell (small, medium, large) in centimeters?

**Comment by Roman45321** [comment]
We used the parcel lockers of "Epicentr" and "Nova Poshta" as examples, took approximate measurements of the lockers and the parcel locker itself. 

Schematically, it looks like this:

![parcel_locker2](https://github.com/user-attachments/assets/0f67c462-c7ac-435d-8bde-dc5c411e372c)




The cells will have the following dimensions:
- Small (16.4 * 10 cm) - 12 units
- Medium (33.2 * 10 cm) - 12 units
- Big (47.4 * 14.6 cm) - 6 units
- Large (47.4 * 15.4 cm) - 10 units
- Extra Large (47.4 * 23.7 cm) - 2 units
- Jumbo (47.4 * 23.7 cm) - 4 units
- Mega (47.4 * 47.4 cm) - 2 units

In total, there are 48 cells in the parcel locker.
