### ISSUE TITLE
When I create Order from Opportuniy I want to copy all product from Opportunity to Order automatically

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#24]
We want to copy all products from Opportunity to Order in an automatic way (when new draft Order record is created).

**Comment by Roman45321** [comment]
The trigger has been created to copy Opportunity Products to new draft Order.

Trigger classes:
OrderTrigger
OrderTriggerHandler
OrderTriggerHelper
OrderTriggerHandlerTest
OrderTriggerHelperTest

Added changes to https://github.com/msenyk/sf-practicum-2024/pull/41 pull request.
