### ISSUE TITLE
Create unit test for CellOrderTrigger

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#27]
Each trigger in Salesforce should have at least 1% of code coverage. Create unit test for trigger on `CellOrder__c` object.

**Comment by Roman45321** [comment]
Created unit-tests CellOrderTriggerHandlerTest and CellOrderTriggerHelperTest for CellOrder__c trigger, added changes to https://github.com/msenyk/sf-practicum-2024/pull/31 pull request.
