### ISSUE TITLE
Delivery team should be able to see which orders are ready to be picked up

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#28]
Delivery team are planning their routes. We need to provide them a tool (Report) that include active orders that are waiting for delivery to parcel lockers.
Group all orders (cell orders) by the Parcel Locker. This task is based on #18.

**Comment by SashaYan10** [comment]
The Report was created to include active orders that are waiting for delivery to parcel lockers and to group Cell Orders by Parcel Locker.

**Comment by msenyk** [comment]
@SashaYan10 Create some Cell Order records in Pending delivery status for different Parcel Lockers,

**Comment by SashaYan10** [comment]
Changes have been made to the Report and Report Type for correct display of Cell Orders with the status "Pending Delivery", and the updates have been added to the pull request https://github.com/msenyk/sf-practicum-2024/pull/53
