### ISSUE TITLE
We need to populate positions of each cell in locker

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#29]
Make sure that all cells have populated Position field.
How can we check that we populated them properly?

**Comment by SashaYan10** [comment]
To check if the Position field is populated, we can:
1) Create a simple validation rule to ensure the Position field is not empty.
2) Create a simple duplicate rule and matching rule to ensure the field is unique.

**Comment by msenyk** [comment]
@SashaYan10 I agree with 1 (idea to have a validation rule). I'm not sure about duplicate and matching rule. This field value is unique across single parcel locker. But for another parcel locker it is have the same value.

**Comment by msenyk** [comment]
Please, populate Position field for all cells of Parcel Locker 123.

**Comment by SashaYan10** [comment]
All position fields were filled.
