### ISSUE TITLE
Set status of the Cell to "Closed" when we mark Cell Order as "Delivered"

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#36]
Delivery service puts the parcel into Cell of Parcel Locker and mark Cell Order status as "Delivered". At this moment we need to mark Cell as "Closed" and set availability as "Full".

**Comment by SashaYan10** [comment]
The Flow for the Cell Order object was created to mark the Cell status as "Closed" and set its availability to "Full" when the Cell Order status is "Delivered".

**Comment by msenyk** [comment]
@SashaYan10 Add link to the pull request, please.

**Comment by SashaYan10** [comment]
I have created a new pull request for this flow: https://github.com/msenyk/sf-practicum-2024/pull/48
