### ISSUE TITLE
When user opens the cell mark the related Cell Order as Completed

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#37]
We assume that after user enters valid PIN code the cell is opened. Change availability of cell to "Empty". If the cell is associated with Cell Order in "Delivered" status - set status of this Cell Order to "Completed".

**Comment by SashaYan10** [comment]
The Flow for the Cell object was created to change the cell availability to "Empty" and set the Cell Order status to "Completed" when the cell is opened and associated with a Cell Order in "Delivered" status.

**Comment by SashaYan10** [comment]
The Flow was added to the pull request.

**Comment by msenyk** [comment]
@SashaYan10 Can you put a link to the pull request in comment?

**Comment by SashaYan10** [comment]
I have created a new pull request for this Flow: https://github.com/msenyk/sf-practicum-2024/pull/49
