### ISSUE TITLE
I want to see how many free space is available in certain parcel locker

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#38]
Each parcel locker has 48 cells. I want to know 2 values:

1. How many cells are occupied (Cell availability is "Full")
2. Percentage of volume of full cells (bigger cells consumes more volume)

Show those values in Utilization section of Parcel Locker page layout.

**Comment by SashaYan10** [comment]
The fields to calculate all cells with "Full" availability and the percentage of the volume of full cells have been added.

**Comment by SashaYan10** [comment]
The type of "Percentage of Volume Occupied" field was changed and changes added to pull request.
