### ISSUE TITLE
Create a service class to wotk with external Parcel Locker REST service

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#39]
This service show have the following public method:

    public Boolean openCell(Integer lockerId, String cellId)
    public Boolean closeCell(Integer lockerId, String cellId)
    public Boolean setPIN(Integer lockerId, String cellId, String pin)

Use Named Credential to define endpoint for external service. You can find URL in the project document.
Each method should call external REST service and return `true` if action is successful. In case of an exception or error - return `false`.
Write a unit test for this service class.

**Comment by Roman45321** [comment]
Created a service class to work with external REST API Parcel Locker service.
Classes (in Org):
ParcelLockerRESTService
ParcelLockerRESTServiceTest
ParcelLockerMock

Named Credential (only for test): ParcelLockerRESTService
