### ISSUE TITLE
Fix Format of Cell auto number Name

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#45]
We have to replace Cyrillic letter in format of Name field of Cell object.
Replace all existing names of Parcel Cell record with number 123.

**Comment by Roman45321** [comment]
Created classes ParcelLockerUtils, ParcelLockerUtilsTest and a method `public void resetCells(String parcelLockerName)` to reinsert existing cells with the correct `Name` value in a Parcel Locker with a specific name.
Reinserted cells in Parcel Locker `123`. Added classes to Org in case it might be needed elsewhere.
