### ISSUE TITLE
Create "Delivery to lockers" app

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#5]
We need to create Lightning Application "Delivery to lockers".
List of tabs: 

- Accounts
- Contacts
- Opportunities
- Orders
- Parcel Lockers

Choose an icon and provide access to System Administrator profile.

**Comment by SashaYan10** [comment]
The "Delivery to lockers" app was created with the tabs **Accounts, Contacts, Opportunities, Orders, Parcel Lockers** and provides access to the System Administrator profile.
