### ISSUE TITLE
Mark Parcel Locker record (Name 123) as ready for integration with Locker Service

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#54]
Not all parcel lockers are integrated with Locker Service REST API. Currently only record with name 123 is available. We have to mark somehow this record. It gives us ability to exclude other records from integration process.

**Comment by SashaYan10** [comment]
The field "Is Integrated" was created to mark Parcel Locker as ready for integration with the Locker Service, and the changes have been added to the pull request https://github.com/msenyk/sf-practicum-2024/pull/57
