### ISSUE TITLE
Name field of Parcel Locker must be unique

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#7]
In #6 we has changed type of Name field of Parcel Locker. This field is not unique anymore. We need to add validation to make sure that user is not able to enter duplicate values. Please check this on insert and edit.

**Comment by Roman45321** [comment]
The trigger has been created to prevent the user from creating parcel lockers with duplicate names (insert, edit).

Trigger classes:
ParcelLockerTrigger
ParcelLockerTriggerHandler
ParcelLockerTriggerHelper
ParcelLockerTriggerHandlerTest
ParcelLockerTriggerHelperTest
Code coverage: 100%

**Comment by msenyk** [comment]
Can you add these files to pull request?

**Comment by Roman45321** [comment]
Added ParcelLocker trigger classes to #8 pull request.

**Comment by Roman45321** [comment]
Added ParcelLocker trigger classes to https://github.com/msenyk/sf-practicum-2024/pull/21 pull request.

**Comment by Roman45321** [comment]
Replaced check for null with use of String.isNotBlank() method in ParcelLockerTriggerHelper class.

**Comment by msenyk** [comment]
@Roman45321 Some unit tests are failed.

**Comment by Roman45321** [comment]
These errors in the CellTriggerHandler test occur because new required fields were added to Cell. I've already fixed this in Org. Should I create a new pull request to make the changes?

**Comment by msenyk** [comment]
> These errors in the CellTriggerHandler test occur because new required fields were added to Cell. I've already fixed this in Org. Should I create a new pull request to make the changes?

This MR is still open. You can add the changes here.
